name: ci

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java env
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Run tests
        run: ./gradlew clean test

      - name: Notify Discord
        uses: sarisia/actions-status-discord@v1
        with:
          webhook:
            ${{ secrets.DISCORD_WEBHOOK_URL }}
        if: failure()